apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

images:
- name: nodeserver
  newName: wericknalyson/gitops
  newTag: 5e096488a71cb393f2886fc6e91f4b79d833ed41
