apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

images:
- name: nodeserver
  newName: wericknalyson/gitops
  newTag: 0808deae5217612788e762c456d51c3871d9f81f
